version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:  # 新增网络配置
      - kafka-net

  zookeeper:
      image: bitnami/zookeeper:3.8
      ports:
        - "2181:2181"
      environment:
        ALLOW_ANONYMOUS_LOGIN: "yes"
        ZOO_INIT_LIMIT: 120  # 增加初始化超时
      networks:
        - kafka-net
      healthcheck:
        test: [ "CMD", "zkServer.sh", "status" ]
        interval: 10s
        timeout: 5s
        retries: 10

  kafka:
      image: bitnami/kafka:3.4
      ports:
        - "9092:9092"
        - "9093:9093"
      environment:
        KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
        KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
        KAFKA_CFG_NUM_PARTITIONS: 3
        KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 1
        KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # 关键配置
        KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      networks:
        - kafka-net
      depends_on:
        zookeeper:
          condition: service_healthy
      healthcheck:
        test: [ "CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092" ]
        interval: 10s
        timeout: 5s
        retries: 10


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      # 移除 cluster.initial_master_nodes 设置
    ports:
      - "9200:9200"
    networks:  # 新增网络配置
      - kafka-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:  # 新增网络配置
      - kafka-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:  # 新增网络配置
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  esdata:
    driver: local