global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'crawler'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
      